# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_001', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='comments',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
