# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_001', '0002_user_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mobile',
            field=models.CharField(default='', max_length=11),
            preserve_default=False,
        ),
    ]
